package enums;

public enum OperationErrorType {

    NO_PARENT,
    NO_ONE_PARENT,
    NULL_ARGUMENT,
    NO_ONE_ARGUMENT,
    PARENT_ERROR,
    PARENT_WITHOUT_COLUMN,
    NO_TWO_PARENTS,
    NO_TWO_ARGUMENTS,
    EMPTY_ARGUMENT,
    NO_PREFIX,
    SAME_SOURCE;
}
